version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: homework_db
      PG_DATA: /var/lib/postgresql/data/
    ports:
      - 5431:5432
    volumes:
      - db:/var/lib/postgresql/data/
volumes:
  db: